### ISSUE TITLE
Computed property names in object destructuring

### ISSUE THREAD

**Issue by bmeurer** [lezer-parser/javascript#12]
The current grammar doesn't support computed property names in object destructuring, for example

```js
const {[Symbol.iterator]: iterator} = array;
```

is valid JavaScript (and TypeScript), but CodeMirror gets highly confused about what it's looking at.

cc @jaro-sevcik

**Comment by marijnh** [comment]
I didn't even know that was a thing! Attached patch adds support.

**Comment by bmeurer** [comment]
Wow, thanks!
