### ISSUE TITLE
`yield` expressions aren't parsed correctly when used with arrays or with `yield*`

### ISSUE THREAD

**Issue by Monkatraz** [lezer-parser/javascript#18]
![image](https://user-images.githubusercontent.com/34875062/208769858-20920296-51c3-4820-b13e-af72de1b0975.png)

https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge2phdmFzY3JpcHR9IGZyb20gIkBjb2RlbWlycm9yL2xhbmctamF2YXNjcmlwdCIKCm5ldyBFZGl0b3JWaWV3KHsKICBkb2M6ICIvLyB3b3JrcyBmaW5lXG5mdW5jdGlvbiogZ2VuKCkge1xuICB5aWVsZCBmb29cbn1cblxuZnVuY3Rpb24qIGdlbigpIHtcbiAgeWllbGQgW11cbn1cblxuZnVuY3Rpb24qIGdlbigpIHtcbiAgeWllbGQgeyBmb286IFtiYXJdIH1cbn1cblxuLy8gYnJlYWtzXG5mdW5jdGlvbiogZ2VuKCkge1xuICB5aWVsZCogZm9vXG59XG5cbmZ1bmN0aW9uKiBnZW4oKSB7XG4gIHlpZWxkIFt2YWxpZF9hcnJheV1cbn1cblxuZnVuY3Rpb24qIGdlbigpIHtcbiAgeWllbGQqIFt2YWxpZF9hcnJheV1cbn1cblxuLy8gd29ya3MgZm9yIHNvbWUgcmVhc29uXG5mdW5jdGlvbiogZ2VuKCkge1xuICB5aWVsZCBbaW52YWxpZF9hcnJheS5dXG59IiwKICBleHRlbnNpb25zOiBbYmFzaWNTZXR1cCwgamF2YXNjcmlwdCgpXSwKICBwYXJlbnQ6IGRvY3VtZW50LmJvZHkKfSkK

You can tell it's not being parsed correctly because the `yield` keyword isn't being highlighted as a keyword sometimes.

Looking at the grammar, it's definitely clear that `yield*` is simply not being handled. I'm not sure what's going on with the array case though, maybe just a dynamic precedence thing?

**Comment by bmeurer** [comment]
It looks like `yield [valid_array]` is parsed as `MemberExpression`, considering `yield` a variable in this context. `yield*` is generally parsed as `BinaryExpression`.

**Comment by marijnh** [comment]
Indeed, the parser was exploring both the case where `yield` (or `await`) was a keyword, and the case where it acted as a variable. For `yield [1]` both were valid, and we needed dynamic precedence to make the outcome predictably choose the keyword rule. Attached patch does this (and adds `yield*` support).
