### ISSUE TITLE
New TypeScript "using" keyword is not highlighted by parser

### ISSUE THREAD

**Issue by tmcw** [lezer-parser/javascript#23]
I can see that this support was added in https://github.com/lezer-parser/javascript/commit/568d51c76ae930ea3ff7edd6699685824fb751b9

However, it doesn't seem to trickle down through to an actual editor - using

```
└─┬ @codemirror/lang-javascript@6.1.9
  └── @lezer/javascript@1.4.7
```

"let" and "const" are properly highlighted, but "using" is not:

![CleanShot 2023-09-22 at 10 08 29@2x](https://github.com/lezer-parser/javascript/assets/32314/f2120b50-b18b-42d4-99c0-7d8fddbeea15)

I'm not sure why - possibly because this is a contextual keyword?

**Comment by marijnh** [comment]
I added it to the grammar but forgot to attach highlighting information to the token. Attached patch does that.

**Comment by marijnh** [comment]
Done!
