### ISSUE TITLE
Support `import { default as name }`

### ISSUE THREAD

**Issue by hyrious** [lezer-parser/javascript#24]
```js
import { default as x } from 'x'
```

It has the same semantics as `import x from 'x'` but is an allowed way of writing. I saw this kind of code from [some outputs of rollup](https://hyrious.me/npm-browser/?q=@antfu/eslint-config@1.0.0-beta.29/package/dist/index.js:8):

```js
import { default as default2 } from "eslint-plugin-antfu";
```

Current AST output:

```
Script
  ImportDeclaration
    import
    ImportGroup
      {
      String
        ⚠
      ⚠
    ⚠
  ExpressionStatement
    VariableName
      ⚠
```

Update: It seems `export { default as name } from 'x'` has this issue too.

**Comment by marijnh** [comment]
This patch should help.

**Comment by bmeurer** [comment]
@marijnh can you tag a release with the fix?

**Comment by marijnh** [comment]
I've tagged 1.4.9!
