### ISSUE TITLE
Incorrect parsing of Typescript unions

### ISSUE THREAD

**Issue by snnsnn** [lezer-parser/javascript#25]
Hi, I was trying to parse some typescript code and came across an inconsistency when parsing unions.

Here is the setup I used. 

```typescript
import { parser as javascriptParser } from "@lezer/javascript"
import { highlightTree, classHighlighter } from "@lezer/highlight"
import type { Tree } from "@lezer/common"

function highlight(str: string, tree: Tree) {
  let result = "", pos = 0
  highlightTree(tree, classHighlighter, (from, to, cls) => {    
    if (from > pos) result += (str.slice(pos, from))
    result += `<span class=${cls}>${(str.slice(from, to))}</span>`
    pos = to
  });
  if (pos < str.length) result += str.slice(pos)
  return result
}

const source = `export type JSONValue =
| number
| null
| boolean
| string;`

const parser = javascriptParser.configure({ dialect: 'ts jsx' });
const tree = parser.parse(source)
const result = highlight(source, tree)
console.log(result);
```

Output:

```html
<span class=tok-keyword>export</span> <span class=tok-keyword>type</span> <span class=tok-typeName>JSONValue</span> <span class=tok-operator>=</span>
| <span class=tok-typeName>number</span>
<span class=tok-operator>|</span> <span class=tok-keyword>null</span>
<span class=tok-operator>|</span> <span class=tok-typeName>boolean</span>
<span class=tok-operator>|</span> <span class=tok-typeName>string</span><span class=tok-punctuation>;</span>
```

Expected Output:

```html
<span class=tok-keyword>export</span> <span class=tok-keyword>type</span> <span class=tok-typeName>JSONValue</span> <span class=tok-operator>=</span>
<span class=tok-operator>|</span> <span class=tok-typeName>number</span>
<span class=tok-operator>|</span> <span class=tok-typeName>null</span>
<span class=tok-operator>|</span> <span class=tok-typeName>boolean</span>
<span class=tok-operator>|</span> <span class=tok-typeName>string</span><span class=tok-punctuation>;</span>
```

As shown above, the first `|`  is treated as text and what follows becomes a keyword.

PS: Although jsx dialect does not serve any purpose, the code I had JSX, so I kept it.

Thank you for this great library and all the work you did.

**Comment by marijnh** [comment]
Attached patch adds support for this.

**Comment by bmeurer** [comment]
Just trying to downstream the patch to Chrome DevTools, but I still see `null` highlighted as keyword instead of type with my little [demo](https://typescript-unions.glitch.me/).

**Comment by marijnh** [comment]
`null` is a keyword, that's intentional. The issue doesn't really say clearly what it's about, but I assumed it was about the misparsing of prefix `|` notation in TS.

**Comment by bmeurer** [comment]
It says _As shown above, the first | is treated as text and what follows becomes a keyword._, so I was assuming that this is both about the incorrect `|` and the incorrect `<span class=tok-keyword>null</span>`.

**Comment by marijnh** [comment]
Types like `null`, `void`, and `this` are all highlighted as keywords. I don't really see a reason to change that—we highlight them as keywords in expression context, the situation in type context is much the same.
