### ISSUE TITLE
Possibly grammar error with TemplateString

### ISSUE THREAD

**Issue by kdog3682** [lezer-parser/javascript#26]
`` const r = RegExp(`^-{${n},}$`, 'm') ``
does not get properly parsed.
I am using lezer 1.4.10.

**Comment by marijnh** [comment]
Can you be more specific than 'does not get properly parsed'? The syntax tree I get for that looks fine.

**Comment by kdog3682** [comment]
You are right. I had preprocessed the string inadverdently.
