### ISSUE TITLE
bitwise operator precedence is wrong

### ISSUE THREAD

**Issue by jedwards1211** [lezer-parser/javascript#27]
This probably doesn't affect anything this grammar is being used for, but FWIW...

The grammar defines precedence

```
  bitOr @left,
  bitXor @left,
  bitAnd @left,
```

But [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence) the correct precedence is

7: bitwise AND | left-to-right | Bitwise ANDx & y
-- | -- | --
6: bitwise XOR | left-to-right | Bitwise XORx ^ y
5: bitwise OR | left-to-right | Bitwise ORx \| y

**Comment by marijnh** [comment]
Thanks for spotting that. Merged.
