### ISSUE TITLE
TS: Support ? for method declarations in interfaces

### ISSUE THREAD

**Issue by SirPepe** [lezer-parser/javascript#37]
The grammar does not appear to understand the `foo?(): number;` bit of the following:

```
interface Test { foo?(): number; }

declare var t: Test;

t.foo() // Cannot invoke an object which is possibly 'undefined'
```

https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgCoQM5mQb2TAewIH4AKASgC5kQBXAWwCNoBuZAXwChOATCBADZwoKAG7DkYauiwtuYAHSECFZAHo1yAMJwQIAtlCiCAaxS7kBRgCt+2AO4ALYAkfJgGZAAcCGDMEYBAE9kAHJaED4YUAgeUKA

**Comment by marijnh** [comment]
Implemented in attached patch. Got any more of these coming or shall I cut a release?

**Comment by marijnh** [comment]
Tagged 1.4.19
