### ISSUE TITLE
Add support for ES2022?

### ISSUE THREAD

**Issue by xianshenglu** [lezer-parser/javascript#40]
Hi,

Thanks for your great work. It really helps a lot.

Maybe just a question, will you support ES2022 and future ES versions?

**Comment by marijnh** [comment]
Which specific types of syntax are you looking to get support for?

**Comment by xianshenglu** [comment]
> Which specific types of syntax are you looking to get support for?

Currently no. 

Just a question regarding whether you'll follow up on the updates in ECMAScript.

After all, it's not easy if keeping updating. Or maybe the syntax doesn't change a lot during updates.

Anyway, thanks for your great work.

**Comment by marijnh** [comment]
> Just a question regarding whether you'll follow up on the updates in ECMAScript.

What I'm trying to understand is why you think that I'm not following updates and why you think this grammar is targeting ES2022 specifically.

**Comment by xianshenglu** [comment]
> > Just a question regarding whether you'll follow up on the updates in ECMAScript.
> 
> What I'm trying to understand is why you think that I'm not following updates and why you think this grammar is targeting ES2022 specifically.

Because I see this in the readme.

> It parses ES2020, and support.....

And you know there're many versions of javascript

- ES2015
- ...
- ES2020
- ...

So, I'm wondering how do you handle the support for different ECMAScript versions.

**According what you said I assume you'll support the latest syntax for ECMAScript?**

So, here comes another question **will you also support old versions of ECMAScript syntax in case one day someone post a syntax issue in old version like ES2015?** For example, `async` is not supported in ES2015.

Anyway, thanks a lot for the response and great work!
