### ISSUE TITLE
TS: Parser error with assertion signatures

### ISSUE THREAD

**Issue by SirPepe** [lezer-parser/javascript#41]
Returns types for assertion functions lead to parse errors:

```typescript
function assert(condition: any): asserts condition {
  if (!condition) {
    throw new Error();
  }
}

function assertIsString(val: any): asserts val is string {
  if (typeof val !== "string") {
    throw new Error("Not a string!");
  }
}
```

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoIIAmMsCAXCmAJ4CUFamOqiBYxpSA3gFCKIzBEuAISt28MDUQ8+fKAAsscAO6IwGVQFEsSrLhoBuXogC+3M91CQOKdNigBJVAGUoWGGADmuAG7IANvTUdLaMUMx+-vzMqG4entLGAkJQVAAOGHCCkYjCALx5iABEse5eRVIysgpKqupaOnB6RQBycFAoiKXxwhVGfGYWhBgQ-shYGIj+GB3AcHBBVADaALqIAD5dcV4baiD+-kbcDPa4c3CG3JbzBogA9HdbZQmbyNSrVyc4Tq7PZ-OXa5wW4PJ7xIA

**Comment by marijnh** [comment]
I wasn't even aware that syntax existed. Attached patch adds support.

**Comment by SirPepe** [comment]
`asserts x is y` works now, but the following still gives me a parse error:

```typescript
function assert(condition: any): asserts condition {
  if (!condition) {
    throw new Error();
  }
}
```

```
Script(FunctionDeclaration(function,VariableDefinition,ParamList("(",VariableDefinition,TypeAnnotation(":",TypeName),")"),TypePredicate(":",asserts,VariableName,⚠),Block("{",IfStatement(if,ParenthesizedExpression("(",UnaryExpression(LogicOp,VariableName),")"),Block("{",ThrowStatement(throw,NewExpression(new,VariableName,ArgList("(",")")),";"),"}")),"}")))
```

**Comment by marijnh** [comment]
All the examples of this I could find used `is`. I cannot find the feature at all in the official docs. Do you have any resource that explains it properly?

**Comment by SirPepe** [comment]
It's mentioned explicitly in the release notes for the relevant version: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

I have never seen it mentioned anywhere else or used in any code, but I believe this is intended as an official feature.

**Comment by marijnh** [comment]
Hrm, mentioning something in a release note and never documenting it is hardly a way to run a software project, if you ask me. But attached patch adds this form.
