### ISSUE TITLE
Add support for const generics

### ISSUE THREAD

**Issue by SirPepe** [lezer-parser/javascript#42]
More wired syntax:

```typescript
function doStuff<const T>(foo:T) {
  return foo;
}

doStuff([1, 2, 3]);

function doOtherStuff<const T extends any[]>(foo:T) {
  return foo;
}

doOtherStuff([1, 2, 3]);
doOtherStuff({ foo: 1 });
```

https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABAEzgZSiYwA8EEDOUiAKgHwAUwccAXCQJSIDeAUIogE4CmmnS1OAG5WAX1atUGLMAoBtAIwAaRACYVAZgC6DEa1CRYCFHADyUABbdO07HkLESibgA8o3MMgKIAhmACeclqUgvRMbBw8fAI0IuKSZpbWtrKKKuqI2roJ5lY2mNgUzIihiAqIorpAA

**Comment by marijnh** [comment]
It would be so great if the TypeScript project published a coherent grammar. But alas, they do not. Attached patch adds support for this notation.
