### ISSUE TITLE
TS: "<" missing when parsing generic arrow functions

### ISSUE THREAD

**Issue by SirPepe** [lezer-parser/javascript#43]
`type identity<T> = T;` turns into the following:

```
Script(TypeAliasDeclaration(type,TypeDefinition,TypeParamList("<",TypeDefinition,">"),Equals,TypeName,";"))
```

This includes the `<` character. 

`const identity = <T> (x: T): T => x;` turns into the following:

```
Script(VariableDeclaration(const,VariableDefinition,Equals,ArrowFunction(TypeParamList(TypeDefinition,">"),ParamList("(",VariableDefinition,TypeAnnotation(":",TypeName),")"),TypeAnnotation(":",TypeName),Arrow,VariableName),";"))
```

Looks like the `<` token has gone AWOL?

**Comment by marijnh** [comment]
The token was missing a name. Attached patch adds it.

Let me know when you think you're done reporting these --- I'll cut another release.

**Comment by SirPepe** [comment]
Done for today, thank you :)
