### ISSUE TITLE
Yarn PnP ambiguous import of @lezer/common

### ISSUE THREAD

**Issue by jakzo** [lezer-parser/javascript#6]
Yarn in PnP mode complains when using this package (and I assume any of the other language packages) with this message:

```
@lezer/javascript tried to access @lezer/common, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

I think this is because an import of `@lezer/common` exists in the generated code but its version is not specified in the package.json, meaning it is unclear which version to use if there happen to be multiple versions of `@lezer/common` in the dependency tree.

**Comment by marijnh** [comment]
Oh, that's annoying. I think the least intrusive way to address it is to set things up so that the output of lezer-generator doesn't directly need to import from common, but that'd involve a breaking change, so it will have to wait until the next breaking release.

**Comment by aegorx** [comment]
same error.

Because the module used in production mode.
