### ISSUE TITLE
Add support for `undefined` highlighting

### ISSUE THREAD

**Issue by lienotly** [lezer-parser/javascript#8]
Hello there,

My team's using this parser as a part of `@codemirror/lang-javascript` with CodeMirror 6 for syntax highlighting.

However, we've noticed that the keyword `undefined` doesn't get highlighted, and while poking around, noticed that this parser's `highlight.js` doesn't seem to associate it with any tag. 

I don't have much context, but from my understanding, if the change isn't much more than adding:
```js
undefined: t.atom,
```
I'd be happy to open a PR!

**Comment by marijnh** [comment]
`undefined` is a regular variable in JavaScript, not a keyword, which I decided to reflect in the grammar.
