### ISSUE TITLE
typescript conditional types

### ISSUE THREAD

**Issue by nicolasgargano** [lezer-parser/javascript#9]
Hi, I ran into some issues while trying out CodeMirror 6 for typescript and I think it's due to this package.

In CodeMirror ([live](https://javascript-lezer-parser-issue.vercel.app), [source](https://github.com/nicolasgargano/javascript-lezer-parser-issue)). Also notice that with jsx enabled it gets confused.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/8648893/175765569-445e2db2-c8bb-4a16-a211-80f5c7821abf.png">

In VSCode/Monaco with a similar theme ([TS Playground](https://www.typescriptlang.org/play?#code/PTAEDkHsBcEsGMCmpoAtkBNYDNuIE6IB2SoARotAO6LErqgAaoAFADaxHIDMAlKAEMiGesgCarDl1AAWXgDoAUIgAeAB0j5oKAJ5rkAUQCOAVwFsAPIwA0oMQD5QAXkWhWFgCr2W-J44+gqtDEGADOTKAA-KAAjKAAXKAATPxBIaGu7l4+zv6BKsHC4RLRcYkpUSj4JsiJ2OahiIqKIBAwCMhomDh4hCTIFNS0RKKgAEScoADWiDqQ2KAeY6CTUsgAHILCo5DSq5zIMTFKrQCCbKGQox4A5OFCIl2gANJ3goSgWLgExNrwkGxNPd4PhIKFwk9oHpEEpVBotLp9KAACKIMgmADmnkcTlAAG9QABtZ4rEYzOYLDwAXUSHmJVNAAF9lOpNNooUiALIEDGIACSREaWlgu1C2OcmQCaSKoEgZAAVoh4NBMm5ogTiaTprN5osaaBufheQKhXBRZ56Y5mW43LSgA)). The pic is from a .tsx file.
<img width="363" alt="image" src="https://user-images.githubusercontent.com/8648893/175764792-913b1e0e-d5ce-473f-81e1-d2df44458df2.png">

I thought it could be the theme but the html also turns out different. For the first example notice that the Y is missing the \<span\>.

(<T>() => T extends X ? 1 : 2) extends             |  (<T>() => T extends Y ? 1 : 2) ? true : false
:-------------------------:|:-------------------------:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/8648893/175766036-d3b22fd8-eb77-4358-9844-9d28e36c0595.png">  |  <img width="243" alt="image" src="https://user-images.githubusercontent.com/8648893/175766064-b87d2473-3f83-4bb5-ba9e-92b23e868d0d.png"> |

I tried adding a simple test case to this parser and it throws `SyntaxError: No parse at 23`. ([TS Playground](https://www.typescriptlang.org/play?ssl=4&ssc=28&pln=1&pc=1#code/C4TwDgpgBAkgzgGQJbAgJwIYBsCCAeAFQD4oBeKAqCAD1QDsATOKAIhxagH4pg0BXaAC4oAM2xwIAKEmhIUHGViIU6bPjYsiM8NAByAe2ALy8ZKky48LAEKagA))
(ignore the expected value, it's from another existing test)
```
# SimpleConditionalType {"dialect": "ts"}

type IsLiteralA<T> = T extends "A" ? true : false

==>

Script(EnumDeclaration(const, enum, TypeDefinition, EnumBody(PropertyName, Equals, Number, PropertyName, PropertyName)))
```

If you agree these are worth fixing, let me know what's the best format to report any other error like this. I'm trying to load stuff from https://github.com/type-challenges/type-challenges into CodeMirror, so I can take notes if I run into issues with some more complicated types.

**Comment by marijnh** [comment]
Attached patches (released in @lezer/javascript 1.0.1) seem to make that snippet parse properly.
